Updated page for Compiler Error CS0116  (#9397)
* clarification
- explained where the logging extension method goes
- minor allignment with the LogQuery method

* applied suggested changes from PR feedback
- removed the *`Extension.cs`* labels
- applied @rpetrusha's suggestions for the LogQuery paragraph

* updated CS0116
- changed code example to be a bit more realistic/scholastic
- included a struct in the code example
- removed language that singled out C/C++ devs

* updated the page
- changed the date
- moved some code around for consistency
- added public modifiers
- updated comments
- specified result of copy-pasting first sample into a code editor (VS)
- added inline link to General Structure of a C# program to text

* updated based on feedback from @pkulikov & @billwagner
- split actual error message from rest of article
- removed "even if" comment, leaving comments on actual error-raising code
- followed proper article date format