There is not a react template for net7.0 or net8.0
I removed net7.0 and net8.0 from the table for angular, react dotnet new template.  This section needs to be further edited.

I get this error for dotnet new react --framework net8.0

Error: Invalid option(s):
--framework net8.0
   'net8.0' is not a valid value for --framework. The possible values are:
      net6.0   - Target net6.0