fix System.IO.IOException error
previous version throwing error:
System.IO.IOException: 'The process cannot access the file because it is being used by another process.'
with SQLite version 3.47.0 and dotnet version 8.0.401

on line 82:
  File.Delete("hello.db");

adding 
SqliteConnection.ClearAllPools(); 
before deleting the file seems to close background connections and release the file to be deleted.