Standardize sample projects, Part 1 (#19260)
* Standardize sample projects, Part 1

* Upgrade netcoreapp3.0

* Fix - error CS1525: Invalid expression term '>'

* Fix - error CS0103: The name 'UnsafeSample' does not exist in the current context

* Fix - error CS0103: The name 'QualifiedName' does not exist in the current context

* Fix - error CS5001: Program does not contain a static 'Main' method suitable for an entry point

* Fix - error CS5001: Program does not contain a static 'Main' method suitable for an entry point

* Add access-by-line.txt